### ISSUE TITLE
Dropbox link does not work 

### ISSUE THREAD

**Issue by mm5223** [KupynOrest/DeblurGAN#119]
The link for downloading weight from Dropbox doesn't seem to work. Can anyone help or share it?

**Comment by fangxu622** [comment]
@gachiemchiep @cclauss @keineahnung2345 @KupynOrest   i also need it ,who can share it ,thanks ,sorry for bother you~

**Comment by gachiemchiep** [comment]
@fangxu622 i still keep the file.
When i come home. i will upload it tonight

**Comment by keineahnung2345** [comment]
@mm5223 @fangxu622 You can download it from https://drive.google.com/open?id=1haX_EdwaqxIrZt-YU-wAcEsAAb8iiHAD.

**Comment by fangxu622** [comment]
oh ``thanks~~@keineahnung2345

**Comment by iamsiddhantsahu** [comment]
@keineahnung2345 I downloaded this file, but was unable to extract it, may be it is corrupted. Pl check.

**Comment by Ji-qing** [comment]
@gachiemchiep  @fangxu622  could you share trained-weight? It is not work from up link

**Comment by Ji-qing** [comment]
@mm5223 @iamsiddhantsahu  @keineahnung2345  
Could you share trained-weight? It is not work from up link

**Comment by keineahnung2345** [comment]
@iamsiddhantsahu @Ji-qing I originally zip it in MacOS, this time I zip it in Linux, please try it: https://drive.google.com/file/d/1liKzdjMRHZ-i5MWhC72EL7UZLNPj5_8Y/view?usp=sharing.

**Comment by flFL12** [comment]
You can't download it from https://drive.google.com/open?id=1haX_EdwaqxIrZt-YU-wAcEsAAb8iiHAD.
Can anyone help or share it?

**Comment by rahulvigneswaran** [comment]
> You can't download it from https://drive.google.com/open?id=1haX_EdwaqxIrZt-YU-wAcEsAAb8iiHAD.
> Can anyone help or share it?@keineahnung2345

I downloaded it today and it is working. What issue are you facing exactly regarding the download?

**Comment by iamsiddhantsahu** [comment]
@rahulvigneswaran Where you able to extract it?

**Comment by rahulvigneswaran** [comment]
@iamsiddhantsahu Yes, indeed. I used the `unzip` command and extracted it via the terminal without any issues. Make sure that your file has been downloaded completely.

**Comment by cclauss** [comment]
Can this issue be closed?

**Comment by rahulvigneswaran** [comment]
Can you people check out issue #130 and provide me with a solution? Did you people run the code successfully? @cclauss @mm5223 @fangxu622
