### ISSUE TITLE
WGAN-GP memory leak？

### ISSUE THREAD

**Issue by hudongloop** [KupynOrest/DeblurGAN#15]
Hi，

I am interested in WGAN-GP, but it has memory [#3858](https://github.com/pytorch/pytorch/issues/3835). Do you have memory leaks when you training the DeblurGAN net.

THANKS!

**Comment by KupynOrest** [comment]
Hello,

We didn't see the memory leak, however, there is a crash due to Pytorch error when parallelizing the model & trying to evaluate Gradient Penalty.
