### ISSUE TITLE
How can I get the output as the same size as input?

### ISSUE THREAD

**Issue by carlblocking** [KupynOrest/DeblurGAN#16]
The output seems to be 256*256 pixel size, how can I get the output as the same size as input?
for example, the input is 500*640, the output I wanna to be 500*640 either.

**Comment by KupynOrest** [comment]
Hello, could you please specify the command which you are running?

Generally, the network output is the same size as the input, if you are talking about blur generation, we are working on updating the code still, however it should work on any size too.

**Comment by carlblocking** [comment]
python test.py --dataroot /.path_to_your_data --model test --dataset_mode single --learn_residual --resize_or_crop scale_width

**Comment by KupynOrest** [comment]
Try this:

python test.py --dataroot /.path_to_your_data --model test --dataset_mode single --learn_residual --resize_or_crop scale_width --fineSize 500 --loadSizeX 500 --loadSizeY 640

And I will try to improve it next week
