### ISSUE TITLE
When I retrain the model ,I meet the error:RuntimeError: cuda runtime error (2) : out of memory at c:\pytorch\torch\lib\thc\generic/THCStorage.cu:66

### ISSUE THREAD

**Issue by benjaminlinken** [KupynOrest/DeblurGAN#17]
Hi,
When I retrain the model ,I meet the error:RuntimeError: cuda runtime error (2) : out of memory at c:\pytorch\torch\lib\thc\generic/THCStorage.cu:66.
My gpu is GTX 1070 8g，my training set includes 1000 pixels with 256 x 256 images, and the default configuration is used for training.Isn't this video card enough to train this model?
THANKS!

**Comment by benjaminlinken** [comment]
I tried to train the model again, and when I changed 'gan_type' from 'wgan-gp' to 'gan', the model could be trained normally.

**Comment by KupynOrest** [comment]
I was trying to run the model on GTX 1080 8g and it was perfectly ok with batch size up to 8.
