### ISSUE TITLE
ConnectionError:HTTPConnectionPool(host='localhost', port=8097)

### ISSUE THREAD

**Issue by hrbspider** [KupynOrest/DeblurGAN#19]
When I train DeblurGAN,I received this error ,while test no this error.
ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /events (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f32c9ce9950>: Failed to establish a new connection: [Errno 111] Connection refused',))
How to solve this problem?

**Comment by hrbspider** [comment]
The problem is that visdom server is not running.
use: `python -m visdom.server` first
[https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/24](url)

**Comment by benjaminlinken** [comment]
Hi,
I also met the question you mentioned, but when I used it：python -m visdom.server，I received this error：
Traceback (most recent call last):
  File "C:\Users\Wu\Anaconda3\lib\site-packages\visdom\server.py", line 669, in download_scripts
    data = opener.open(req).read()
  File "C:\Users\Wu\Anaconda3\lib\urllib\request.py", line 466, in open
    response = self._open(req, data)
  File "C:\Users\Wu\Anaconda3\lib\urllib\request.py", line 484, in _open
    '_open', req)
  File "C:\Users\Wu\Anaconda3\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\Wu\Anaconda3\lib\urllib\request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Users\Wu\Anaconda3\lib\urllib\request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>                                                                                                    

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Wu\Anaconda3\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Wu\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Wu\Anaconda3\lib\site-packages\visdom\server.py", line 690, in <module>
    download_scripts()
  File "C:\Users\Wu\Anaconda3\lib\site-packages\visdom\server.py", line 673, in download_scripts
    logging.error('Error {} while downloading {}'.format(exc.code, key))
AttributeError: 'URLError' object has no attribute 'code'

**Comment by hrbspider** [comment]
@benjaminlinken I should modify my answer.  I also have received the following  'AttributeError: 'URLError' object has no attribute 'code' error. 
I commented `download_scripts()` at the end part of server.py and it works.
```
End of epoch 6 / 300 	 Time Taken: 173 sec
PSNR on Train = 28.893842
(epoch: 7, iters: 210, time: 0.192) G_GAN: 59.480 G_L1: 1243.840 D_real+fake: -53.398 
PSNR on Train = 27.676232
(epoch: 7, iters: 510, time: 0.197) G_GAN: 64.746 G_L1: 1006.709 D_real+fake: -100.703 
PSNR on Train = 28.006452
(epoch: 7, iters: 810, time: 0.203) G_GAN: 58.397 G_L1: 963.713 D_real+fake: -60.652 
End of epoch 7 / 300 	 Time Taken: 174 sec
PSNR on Train = 28.240143
(epoch: 8, iters: 45, time: 0.200) G_GAN: 60.385 G_L1: 1012.398 D_real+fake: -73.799 

```

**Comment by benjaminlinken** [comment]
@hrbspider It works for me. Thank you very much !

**Comment by yff0815** [comment]
> @benjaminlinken I should modify my answer. I also have received the following 'AttributeError: 'URLError' object has no attribute 'code' error.
> I commented `download_scripts()` at the end part of server.py and it works.
> 
> ```
> End of epoch 6 / 300 	 Time Taken: 173 sec
> PSNR on Train = 28.893842
> (epoch: 7, iters: 210, time: 0.192) G_GAN: 59.480 G_L1: 1243.840 D_real+fake: -53.398 
> PSNR on Train = 27.676232
> (epoch: 7, iters: 510, time: 0.197) G_GAN: 64.746 G_L1: 1006.709 D_real+fake: -100.703 
> PSNR on Train = 28.006452
> (epoch: 7, iters: 810, time: 0.203) G_GAN: 58.397 G_L1: 963.713 D_real+fake: -60.652 
> End of epoch 7 / 300 	 Time Taken: 174 sec
> PSNR on Train = 28.240143
> (epoch: 8, iters: 45, time: 0.200) G_GAN: 60.385 G_L1: 1012.398 D_real+fake: -73.799 
> ```
你好，请问server.py文件是在项目目录下自己创立的吗？

**Comment by yff0815** [comment]
> @benjaminlinken I should modify my answer. I also have received the following 'AttributeError: 'URLError' object has no attribute 'code' error.
> I commented `download_scripts()` at the end part of server.py and it works.
> 
> ```
> End of epoch 6 / 300 	 Time Taken: 173 sec
> PSNR on Train = 28.893842
> (epoch: 7, iters: 210, time: 0.192) G_GAN: 59.480 G_L1: 1243.840 D_real+fake: -53.398 
> PSNR on Train = 27.676232
> (epoch: 7, iters: 510, time: 0.197) G_GAN: 64.746 G_L1: 1006.709 D_real+fake: -100.703 
> PSNR on Train = 28.006452
> (epoch: 7, iters: 810, time: 0.203) G_GAN: 58.397 G_L1: 963.713 D_real+fake: -60.652 
> End of epoch 7 / 300 	 Time Taken: 174 sec
> PSNR on Train = 28.240143
> (epoch: 8, iters: 45, time: 0.200) G_GAN: 60.385 G_L1: 1012.398 D_real+fake: -73.799 
> ```
Hi,
I also met the question you mentioned, but i would like to know where is the server.py ?
