### ISSUE TITLE
Pre-trained weights and Inference 

### ISSUE THREAD

**Issue by innat** [KupynOrest/DeblurGAN#197]
Even in ReadMe, it says the weight files are stored in google drive, surely it's not there. Files are located now simply in the following directories: `DeblurGAN/checkpoints/experiment_name/`, namely: `latest_net_D.pth` and `latest_net_G.pth`.

In inference time, what I have found that the model randomly crops the image, practically which is not desirable. Is there any workaround to get results with the pre-trained weights on the entire input (blurred) sample?

**Comment by SuJiaKuan** [comment]
Please try to run `test.py` with `--resize_or_crop scale_width` parameter.

Example:

```bash
python test.py --dataroot /.path_to_your_data --model test --dataset_mode single --resize_or_crop scale_width --learn_residual
```
