### ISSUE TITLE
ImportError: cannot import name 'SSIM'

### ISSUE THREAD

**Issue by dapsjj** [KupynOrest/DeblurGAN#20]
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    from ssim import SSIM
ImportError: cannot import name 'SSIM'

There is no error when I enter import SSIM at CMD window.
How to fix the error?

**Comment by SongyiGao** [comment]
You can use from ssim import ssim as SSIM. I have used it and it can work.

**Comment by dapsjj** [comment]
It should be "from util.metrics import SSIM"
