### ISSUE TITLE
What does unaligned, aligned, single represent in the dataset_mode?

### ISSUE THREAD

**Issue by benjaminlinken** [KupynOrest/DeblurGAN#21]
What does unaligned, aligned, single represent in the dataset_mode?

**Comment by KupynOrest** [comment]
Hello, 
aligned dataset it the output of combineA_and_B script which produce one image containing with corresponding blurred and sharp photos
unaligned dataset is used for training when you have images of class A and B in different folders and single dataset is used for testing assuming you have only the images from class A (blurred photos)

**Comment by TrinhSaiki** [comment]
Hello KupynOrest, 
Thank you for your awesome code, I am retraining the model using my own data. If I use the mode: aligned, I have to put in the "train" folder the images which have width x height = 200 x 100 for example.

In each image, it consists of 2 part: 100 x 100 for blurry image in the left and 100 x 100 for sharp image in the right. Then I run this command: python train.py --dataroot ./datasets/train --which_direction AtoB --fineSize 100 --loadSizeX 200 --loadSizeY 100

Is there any steps which I am doing wrongly (especially the command)? 
Thank you.

**Comment by KupynOrest** [comment]
@TrinhSaiki 

**1.** It seems that everything is okay here, does it work?
**2.** We can, but for training, I crop the patch of 256x256 to speed up the training process, also the recommended size to increase the efficiency in pytorch should be a power of 2, so depending on your computational resources I would recommend training on 256x256 or 512x512 patches.

**Comment by TrinhSaiki** [comment]
Hi KupynOrest,
Thank for reply. 
**1.** I am training the model,  apparently it is working, but I have to wait to see how it'll be looked like.
**2.** Thank you, I understood the reason why.. I just a bit worry for losing data of the images, but it seems that it's not the big deal.
**3.** Do you think that we can make it real time for the video (using opencv)

**Comment by KupynOrest** [comment]
Actually, you are not losing any data as the model is applied convolutionally to a bigger image, so you can train on image patches and then test on the full image.
I am not sure about the real time as I haven't tested the performance in different settings, in my scenario the inference time is 0.3~0.8sec. on different GPU and on images from 640x360 to 1280x720 size, so you might try, I would be super interested to see the results.
However, if you need it specifically for video deblurring, there are other methods that can benefit from the additional information.

**Comment by TrinhSaiki** [comment]
Hi KupynOrest,
Thanks for your reply. One image per 0.3~0.8sec, that means 1.25 - 3.3 frames/second and in order to bust to process real time video is likely impossible. 
Yes, could you tell me some of those methods to process the blurry video. As I know that the YOLO model can do real time (in classification tasks), what do you think about these GAN models, how can we make it process real time videos.
Thank you.

**Comment by TrinhSaiki** [comment]
Hi KupynOrest,
I've found that my command did not use: --residual_learn, but in the test command you have showed, It has --residual_learn. It should be better to learn with --residual_learn, isn't it?

**Comment by KupynOrest** [comment]
@TrinhSaiki I am currently investigating the possibilities to run my model in real time, however, for Video Deblurring you can take a look at this paper - [https://arxiv.org/abs/1611.08387](url) 

Also, in our work, we find that the global residual connection allows restoring finer texture details better so it should be better to learn with --learn_residual, but you still should be able to get pretty good results even without it.

**Comment by TrinhSaiki** [comment]
Dear KupynOrest, 
Thank you for your reply, I have read the paper. Yes, It processed on the video, but not real time. 
I have tried another GAN models, but it seems that at the moment, I have not found any papers which describe processing the real time videos (which are captured from cameras), Do you know any?

Thank you for your hard work.

**Comment by KupynOrest** [comment]
@TrinhQuocNguyen 
Sorry for the late reply. You can take a look at this paper - https://arxiv.org/abs/1801.05117 which uses our work. To make it suitable for real time you'd need to optimize the generator (use lightweight architecture for example instead of ours.) If you still have some questions feel free to send me the message
