### ISSUE TITLE
How to decide when to stop training?

### ISSUE THREAD

**Issue by hrbspider** [KupynOrest/DeblurGAN#24]
From my experience in classification training, the val data is used to decide when to stop during training on train data. But in deblurGAN I haven't found this mechanics.
So how to decide to stop training?

**Comment by KupynOrest** [comment]
The problem is that in contrast to Object Recognition, for example, it is quite complicated to choose the metric for early stopping as PSNR for example often does not correspond with visual quality. However, it might be possible to use perceptual loss on a validation set as the stopping criterion.
