### ISSUE TITLE
 No module named 'dominate'

### ISSUE THREAD

**Issue by WuJunde** [KupynOrest/DeblurGAN#25]
I meet the error
util/html.py", line 1, in <module>
    import dominate
ModuleNotFoundError: No module named 'dominate'

By the way, if I want to run it on CPU,where I need to change?

Thank you.

**Comment by keineahnung2345** [comment]
For the first question, you can just type "pip install dominate" in your command line.
For the second question, I tried adding ”--gpu_ids -1“ when calling "python test.py", but I got the following error:

Traceback (most recent call last):
  File "test.py", line 38, in <module>
    model.set_input(data)
  File "/root/DeblurGAN/models/test_model.py", line 31, in set_input
    self.input_A.resize_(input_A.size()).copy_(input_A)
RuntimeError: calling resize_ on a tensor that has non-resizable storage. Clone it first or create a new tensor instead.

**Comment by keineahnung2345** [comment]
I've found a quick hack to the problem of resize_().
Just replace
`self.input_A.resize_(input_A.size()).copy_(input_A)`
into
```
temp = self.input_A.clone()
temp.resize_(input_A.size())
self.input_A = temp
```

**Comment by WuJunde** [comment]
Thank you. I've run it on my CPU. it's faster than I expected.

**Comment by KupynOrest** [comment]
@keineahnung2345 thanks for the pack for CPU, unfortunately, we didn't have enough time to test it properly on CPU.

**Comment by keineahnung2345** [comment]
You're welcome. I am glad to be able to help someone in the other end of internet.

**Comment by keineahnung2345** [comment]
@KupynOrest I just made a pull request, will you consider to merge it?
https://github.com/KupynOrest/DeblurGAN/pull/28

**Comment by KupynOrest** [comment]
Already merged, thanks for your fix!

**Comment by SalarYakamoz** [comment]
> I meet the error
> util/html.py", line 1, in 
> import dominate
> ModuleNotFoundError: No module named 'dominate'
> 
> By the way, if I want to run it on CPU,where I need to change?
> 
> Thank you.

I had the same problem and solved by using "conda install visdom dominate -c conda-forge"
