### ISSUE TITLE
On the detailed operation

### ISSUE THREAD

**Issue by CAAlexChang** [KupynOrest/DeblurGAN#29]
Hello, I am a beginner. How can I add dataroot to the environment, and I want to turn my blurred picture into clear image. Which folder should I put into it and and what commands to input to Python?

The following is my mistake
[-h] --dataroot DATAROOT [--batchSize BATCHSIZE]
               [--loadSizeX LOADSIZEX] [--loadSizeY LOADSIZEY]
               [--fineSize FINESIZE] [--input_nc INPUT_NC]
               [--output_nc OUTPUT_NC] [--ngf NGF] [--ndf NDF]
               [--which_model_netD WHICH_MODEL_NETD]
               [--which_model_netG WHICH_MODEL_NETG] [--learn_residual]
               [--gan_type GAN_TYPE] [--n_layers_D N_LAYERS_D]
               [--gpu_ids GPU_IDS] [--name NAME] [--dataset_mode DATASET_MODE]
               [--model MODEL] [--which_direction WHICH_DIRECTION]
               [--nThreads NTHREADS] [--checkpoints_dir CHECKPOINTS_DIR]
               [--norm NORM] [--serial_batches]
               [--display_winsize DISPLAY_WINSIZE] [--display_id DISPLAY_ID]
               [--display_port DISPLAY_PORT]
               [--display_single_pane_ncols DISPLAY_SINGLE_PANE_NCOLS]
               [--no_dropout] [--max_dataset_size MAX_DATASET_SIZE]
               [--resize_or_crop RESIZE_OR_CROP] [--no_flip] [--ntest NTEST]
               [--results_dir RESULTS_DIR] [--aspect_ratio ASPECT_RATIO]
               [--phase PHASE] [--which_epoch WHICH_EPOCH]
               [--how_many HOW_MANY]
test.py: error: the following arguments are required: --dataroot

**Comment by TrinhSaiki** [comment]
What was your command to run?

**Comment by KupynOrest** [comment]
Assuming that you have a folder inside DeblurGAN called "blurry_images" `DeblurGAN/blurry_images` and you have downloaded the weights

Your command should be: `python test.py --dataroot /.blurry_images --model test --dataset_mode single --learn_residual`

**Comment by CAAlexChang** [comment]
@KupynOrest  Hello, thank you for your reply
 I don't know where to enter 
`/.checkpoints/experiment_name`

**Comment by CAAlexChang** [comment]
@TrinhSaiki Run the test.py

**Comment by overid40** [comment]
Hi, I'm a beginner.
I don't know where to enter
/.checkpoints/experiment_name
Please, Answer it!

**Comment by overid40** [comment]
@KupynOrest 
Hi, I am a beginner.

I don't know how to put weights into "/.checkpoints/experiment_name"
and
where "/.checkpoints/experiment_name" is.

Please, answer it!
