### ISSUE TITLE
ImportError: cannot import name 'SSIM'

### ISSUE THREAD

**Issue by hust-lidelong** [KupynOrest/DeblurGAN#30]
Hello!
When I run train.py in command line,I meet this problem. What shold I do?

>>python test.py --dataroot ./test --model test --dataset_mode single --learn_residual

Traceback (most recent call last):
  File "test.py", line 10, in <module>
    from ssim import SSIM
ImportError: cannot import name 'SSIM'

**Comment by KupynOrest** [comment]
Hello,
Try `pip install pyssim`

**Comment by hust-lidelong** [comment]
Thanks a lot! You are right.This problem has been solved.
But I meet another problem.What should I do?

netG.cuda(device_id=gpu_ids[0])
TypeError: cuda() got an unexpected keyword argument 'device_id'

**Comment by KupynOrest** [comment]
There is an incompatibility in pytorch between tensor and variable - https://github.com/pytorch/pytorch/issues/2685

Try to change from device_id to device, but I am not sure that it would help

**Comment by hust-lidelong** [comment]
Hello KupynOrest
Your advice is right.Thanks!
Can you tell me  how to prepare train data and  train DeblurGAN? Because the result image is not satisfactory.Thanks!

**Comment by KupynOrest** [comment]
I have updated the README with the instructions, please send me the message if you have any additional questions, thanks

**Comment by dhnesh12** [comment]
use from util.metrics import SSIM
