### ISSUE TITLE
Generator model

### ISSUE THREAD

**Issue by diegotessarollo** [KupynOrest/DeblurGAN#32]
Could you share the latest_net_G weights? 
Thanks

**Comment by hhliao** [comment]
I am also get the Error:  No such file or directory: './checkpoints/experiment_name/latest_net_G.pth'

**Comment by hrbspider** [comment]
I also need the latest_net_G weights to do a test. Could you please share the file？ 
Thanks.

**Comment by nk0307** [comment]
yeah. really need that. since it is not working for D

**Comment by KupynOrest** [comment]
Already updated the link with the weights, please tell if you still can not download the latest model, thanks.

**Comment by DecentMakeover** [comment]
Hi 
Not able to download the model via Dropbox, i think the link is broken.Can you check please.
