### ISSUE TITLE
The grid effect exists in the generate images. How to fix it？

### ISSUE THREAD

**Issue by shenqixiaojiang** [KupynOrest/DeblurGAN#41]
![image](https://user-images.githubusercontent.com/9745477/35903838-c9207a76-0c1b-11e8-8cd2-f5e242656648.png)

Just like the above image, the grid effect exists in the generate images, which make the generate images seem to be not natural. Would you meet this situation, and how to fix it? 

Thank you.

**Comment by KupynOrest** [comment]
Hello,
The checkerboard artifacts are the results of Deconv/TrasposedConvolution operation. They can be minimized by using more advanced upsampling methods, such as [SubPixelConvolution](https://arxiv.org/abs/1609.05158) or [Bilinear Additive Upsampling](https://arxiv.org/abs/1707.05847). Unfortunately, I didn't have enough time to try them and see if that helps, I would appreciate if you can share the results of your models with those UpConv blocks or I would try to add it in the nearest future

**Comment by shenqixiaojiang** [comment]
@KupynOrest This phenomenon existed when I tested your test model on my datasets. 

The original image: 
![2437380332_real_a](https://user-images.githubusercontent.com/9745477/36015626-3568d068-0daa-11e8-849f-db8c4a88f6e9.png)

 The output of your test model:
![2437380332_fake_b](https://user-images.githubusercontent.com/9745477/36015659-61124744-0daa-11e8-8d69-af6199245c84.png)

It seems that not only the motion blur but also the gaussian blur existed in the above image, which make the grid effect is obvious. 
And in the next step, I want to use the image sharpening to improve the  output.

**Comment by jiangzidong** [comment]
I have the same issue. @KupynOrest Could you please provides the example code to reproduce the great results in your paper? Thanks

**Comment by KupynOrest** [comment]
@jiangzidong for Kohler test try to run the model on downscaled b ya factor of 2 images as we did on the train, and upscale afterwards, the problem might be that the latest model was trained on a different scale, we added that part to the latest version of our paper.
Regarding checkerboard artifacts, I've updated the model parameters to deal with that problems, the other solution might be using PixelShuffle as in SRGAN or simply train longer.

**Comment by ruiwen0615** [comment]
@KupynOrest Thanks for your reply. I didn't do any training, and directly used your trained weights, why I cannot reproduce your result? You mentioned that we may need to downscale image by 2, could we just change options --loadSizeX and --loadSizeY to achieve downscaling? I tried this, but I still can see checker patterns. Please give more details about it. Thanks.

**Comment by xiaozhi2015** [comment]
The half-resolution test doesn't make better result. @KupynOrest 
Have you solved the grid effect? @shenqixiaojiang

**Comment by shenqixiaojiang** [comment]
@xiaozhi2015 不好意思，这个问题没有得到很好的解决方式。

**Comment by xiaozhi2015** [comment]
Thx for your reply anyway. Besides, the author has released "DeblurGAN-v2", which is "Faster and Better" and more stable in my experience. @shenqixiaojiang
