### ISSUE TITLE
new code for PSNR

### ISSUE THREAD

**Issue by SivanDoveh** [KupynOrest/DeblurGAN#45]
hi!
if i want to run psnr calculation on some dataset how can i do it?
thanks!

**Comment by nickolaymykhalych** [comment]
`def PSNR(img1, img2):
	mse = np.mean( (img1/255. - img2/255.) ** 2 )
	if mse == 0:
		return 100
	PIXEL_MAX = 1
	return 20 * math.log10(PIXEL_MAX / math.sqrt(mse))`
img1 and img2 is numpy array.
