### ISSUE TITLE
How to test rectangle images, the "fine size" parameter seems to make the output only square.

### ISSUE THREAD

**Issue by Heyi007** [KupynOrest/DeblurGAN#48]

**Comment by KupynOrest** [comment]
please tune fineSizeX/Y parameters

**Comment by obelling** [comment]
@KupynOrest I had not find fineSizeX/Y parameters,please tell me how to tune it?

**Comment by Mrmachiner** [comment]
> @KupynOrest I had not find fineSizeX/Y parameters,please tell me how to tune it?

open options/base_options.py bro
