### ISSUE TITLE
contrast algorithm

### ISSUE THREAD

**Issue by Pkeng** [KupynOrest/DeblurGAN#49]
Thanks for your great  work. I·m collecting the latest algorithms about learning to deblur. And could you tell me where did you get the algorithm for the program "Learning a Convolutional Neural Network for Non-uniform Motion Blur Rmoval" used  in your contrast experiment .Did you realize it yourself?

**Comment by KupynOrest** [comment]
thanks for your interest, no we didn't, but you could send a message to the authors and requests the code or the results for the research purpose.
