### ISSUE TITLE
Backward twice when using wgan-gp as critic

### ISSUE THREAD

**Issue by Gasoonjia** [KupynOrest/DeblurGAN#56]
I encountered the following error when using wgan-gp as discriminator and everything went well whe using other discriminator:
Traceback (most recent call last):
  File "train.py", line 42, in <module>
    model.optimize_parameters()
  File "/home/gasoon/code/research/VideoDeblur/models/conditional_gan_model.py", line 136, in optimize_parameters
    self.backward_D()
  File "/home/gasoon/code/research/VideoDeblur/models/conditional_gan_model.py", line 110, in backward_D
    self.loss_D.backward()
  File "/home/gasoon/anaconda3/envs/vd/lib/python3.6/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/gasoon/anaconda3/envs/vd/lib/python3.6/site-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

I'm using the data generated by myself whose resolution is 640*480.
Does anyone know the way to solve it? Thank you so much!

**Comment by Gasoonjia** [comment]
btw, pytorch version is 0.40 and python version is 3.6.5

**Comment by KupynOrest** [comment]
It seems that the bug is only with the new pytorch version, because the WGAN discriminator is updated multiple times on each Generator update, I can't give a hotfix right now, but I would try to investigate the problem

**Comment by yueruchen** [comment]
Hi @Gasoonjia , @KupynOrest 

The code about wgan-gp discriminator is confused, in the file `losses.py`, there is a class:
def get_loss(self, net, realA, fakeB, realB):
		self.D_fake = net.forward(fakeB.detach())
		self.D_fake = self.D_fake.mean()
		
		# Real
		self.D_real = net.forward(realB)
		self.D_real = self.D_real.mean()
		# Combined loss
		self.loss_D = self.D_fake - self.D_real
		gradient_penalty = self.calc_gradient_penalty(net, realB.data, fakeB.data)
		return self.loss_D + gradient_penalty

As you can see, `self.D_fake` is just the output of network D. However, it should be computed by the loss such as MSEloss or BCE loss. The problem also occurred on `self.D_real`. I think it should be another line here, something like `self.D_fake_loss = self.loss(self.D_fake, 0)` 

Could you please help me answer this question?

**Comment by Gasoonjia** [comment]
@yueruchen
The part make you confused is exact the shining part of wgan.
In the wgan and its formal paper, the author found that using the loss you provided may cause the gan model collapses. For instance, the gan model may generates the same "save sample" no matter what the input is to get a low gan loss. In the wgan, the author replaced the traditional loss with Wasserstein distance to overcome the above problem, and that is the self.loss_D in your comment.
The following page in zhihu may help you to understand the wgan and the principle and mathematical derivation behind it.
https://zhuanlan.zhihu.com/p/25071913

**Comment by Gasoonjia** [comment]
There is a loss function, which is loss_D, aka wasserstein disrance,  in the code.
In the ideal situation, the wasserstein distance between the distribution of generated field and target should be zero, just like the cross entropy between generated item and target item should be zero. So in wgan, we use this as the loss between two field.

**Comment by yueruchen** [comment]
@Gasoonjia 
Thanks!
I know what you mean.

**Comment by gachiemchiep** [comment]
@Gasoonjia 
I occurred this type of error too. Fix in https://github.com/KupynOrest/DeblurGAN/pull/91
