### ISSUE TITLE
Would you please release the code you used for motion blur kernel generation?

### ISSUE THREAD

**Issue by Gasoonjia** [KupynOrest/DeblurGAN#62]
I have done some little work on image debluring and I plan to use your powerful method to generate some sharp-blur image pairs for training. But I can not implement the code perfectly if only basing on the Algorithm in your paper. So would you please release the code you used for motion blur kernel generation? Thank you so much for your generous help.

**Comment by Gasoonjia** [comment]
If you are not will to make your code public, would you mind sending them to me privately? My email address is gasoonjia@icloud.com. I really need your help. Thanks again.

**Comment by KupynOrest** [comment]
The code is in motion_blur folder. Should you have any questions, don't hesitate to contact us through e-mail.
