### ISSUE TITLE
use_parallel is an undefined name in test_model.py

### ISSUE THREAD

**Issue by cclauss** [KupynOrest/DeblurGAN#7]
https://github.com/KupynOrest/DeblurGAN/search?utf8=%E2%9C%93&q=use_parallel&type=

https://github.com/KupynOrest/DeblurGAN/blob/master/models/test_model.py#L18

flake8 testing of https://github.com/KupynOrest/DeblurGAN on Python 2.7.14

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./models/test_model.py:18:105: F821 undefined name 'use_parallel'
                                      opt.which_model_netG, opt.norm, not opt.no_dropout, self.gpu_ids, use_parallel,
                                                                                                        ^
```

**Comment by mersaint** [comment]
I met the same problem. If I set use_parallel = 1, it went ahead, but I wonder whether appropriate or not.

**Comment by ARSwhut** [comment]
I met the same problem.

**Comment by Hanimiao** [comment]
I met the same problem too.

**Comment by Hanimiao** [comment]
@cclauss Do you solve this problem?

**Comment by Hanimiao** [comment]
@mersaint Where to modify the settings?

**Comment by KupynOrest** [comment]
Fixed the issue in latest commit
