### ISSUE TITLE
Which model is the best to use for moving object in the image?

### ISSUE THREAD

**Issue by shivam2296** [KupynOrest/DeblurGAN#75]
The code performs well when there is  a camera shake. But poorly on moving objects. How do you solve that? Which model should we use?
I'm currently using the model 'test'.
If I try to change the model, I face this error-
______________________________________________________________________________
   Traceback (most recent call last):
  File "test.py", line 35, in <module>
    model.set_input(data)
  File "/home2/shivam/DeblurGAN/models/conditional_gan_model.py", line 69, in set_input
    input_B = input['B' if AtoB else 'A']
KeyError: 'B'
______________________________________________________________________________

**Comment by KupynOrest** [comment]
Hello,
Unfortunately you can not change the model to the different one, due to the dataset bias and limited computational resources we had, the model is performing on some kind of scenes better than on the others.
