### ISSUE TITLE
Unexpected results when using weights downloaded from the dropbox link.

### ISSUE THREAD

**Issue by SophiaSarah** [KupynOrest/DeblurGAN#79]
Using weights from Dropbox link, I got unexpected results when deblurring images from GoPro and YOLO dataset as same as ones in the _./DeblurGAN/images/_. Is there anything wrong?
***@***:~/DeblurGAN$ python test.py --dataroot ./images/test/ --model test --dataset_mode single --learn_residual --resize_or_crop no_change
------------ Options -------------
aspect_ratio: 1.0
batchSize: 1
checkpoints_dir: ./checkpoints
dataroot: ./images/test/
dataset_mode: single
display_id: 1
display_port: 8097
display_single_pane_ncols: 0
display_winsize: 256
fineSize: 256
gan_type: wgan-gp
gpu_ids: [0]
how_many: 5000
input_nc: 3
isTrain: False
learn_residual: True
loadSizeX: 640
loadSizeY: 360
max_dataset_size: inf
model: test
nThreads: 2
n_layers_D: 3
name: experiment_name
ndf: 64
ngf: 64
no_dropout: False
no_flip: False
norm: instance
ntest: inf
output_nc: 3
phase: test
resize_or_crop: no_change
results_dir: ./results/
serial_batches: False
which_direction: AtoB
which_epoch: latest
which_model_netD: basic
which_model_netG: resnet_9blocks
-------------- End ----------------
CustomDatasetDataLoader
dataset [SingleImageDataset] was created
---------- Networks initialized -------------
……
-----------------------------------------------
model [TestModel] was created
[2018-06-20 16:05:32,425] INFO: Socket refused connection, running socketless
process image... ['./images/test/test1_b.jpg']
process image... ['./images/test/yolo_b.jpg']
————————————-————————————————————————
My results are as followed:
test1_b.jpg
![test1_b](https://user-images.githubusercontent.com/26705571/41646451-6a3e3b80-74a6-11e8-92de-2e7deb520853.jpg)

test1_b_fake_B.png
![test1_b_fake_b](https://user-images.githubusercontent.com/26705571/41646485-8436d8ee-74a6-11e8-87e4-047f15b156ca.png)

The corresponding result as you've shown:
![test1_restored](https://user-images.githubusercontent.com/26705571/41647452-05e01a66-74a9-11e8-852c-6cc6e80fc986.jpg)

yolo_b.jpg
![yolo_b](https://user-images.githubusercontent.com/26705571/41646526-a15da862-74a6-11e8-82ce-bbf7a57247b0.jpg)

yolo_b_fake_B.png
![yolo_b_fake_b](https://user-images.githubusercontent.com/26705571/41646550-b16fd4a0-74a6-11e8-98be-e2801c1e98ca.png)

The corresponding result as you've shown:
![yolo_o](https://user-images.githubusercontent.com/26705571/41647487-1c8f1406-74a9-11e8-832c-02d012d17e94.jpg)

**Comment by KupynOrest** [comment]
Hello, I've compressed & changed those images to put into paper, so you may not receive good results on them, please try to run the model on original images
