### ISSUE TITLE
Test problem

### ISSUE THREAD

**Issue by Harry-675** [KupynOrest/DeblurGAN#80]
I met the following problem when run the test.py,how can I solve it?
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    model = create_model(opt)
  File "/home/harry/Project/DeblurGAN-master (1)/DeblurGAN-master/models/models.py", line 11, in create_model
    model.initialize(opt)
  File "/home/harry/Project/DeblurGAN-master (1)/DeblurGAN-master/models/test_model.py", line 21, in initialize
    self.load_network(self.netG, 'G', which_epoch)
  File "/home/harry/Project/DeblurGAN-master (1)/DeblurGAN-master/models/base_model.py", line 53, in load_network
    network.load_state_dict(torch.load(save_path))
  File "/home/harry/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResnetGenerator:
        Unexpected running stats buffer(s) "model.2.running_mean" and "model.2.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "model.5.running_mean" and "model.5.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "model.8.running_mean" and "model.8.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "model.10.conv_block.2.running_mean" and "model.10.conv_block.2.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "model.10.conv_block.7.running_mean" and "model.10.conv_block.7.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "model.11.conv_block.2.running_mean" and "model.11.conv_block.2.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "model.11.conv_block.7.running_mean" and "model.11.conv_block.7.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "model.12.conv_block.2.running_mean" and "model.12.conv_block.2.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "model.12.conv_block.7.running_mean" and "model.12.conv_block.7.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "model.13.conv_block.2.running_mean" and "model.13.conv_block.2.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "model.13.conv_block.7.running_mean" and "model.13.conv_block.7.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "model.14.conv_block.2.running_mean" and "model.14.conv_block.2.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "model.14.conv_block.7.running_mean" and "model.14.conv_block.7.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "model.15.conv_block.2.running_mean" and "model.15.conv_block.2.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "model.15.conv_block.7.running_mean" and "model.15.conv_block.7.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "model.16.conv_block.2.running_mean" and "model.16.conv_block.2.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "model.16.conv_block.7.running_mean" and "model.16.conv_block.7.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "model.17.conv_block.2.running_mean" and "model.17.conv_block.2.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "model.17.conv_block.7.running_mean" and "model.17.conv_block.7.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "model.18.conv_block.2.running_mean" and "model.18.conv_block.2.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "model.18.conv_block.7.running_mean" and "model.18.conv_block.7.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "model.20.running_mean" and "model.20.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.
        Unexpected running stats buffer(s) "model.23.running_mean" and "model.23.running_var" for InstanceNorm2d with track_running_stats=False. If state_dict is a checkpoint saved before 0.4.0, this may be expected because InstanceNorm2d does not track running stats by default since 0.4.0. Please remove these keys from state_dict. If the running stats are actually needed, instead set track_running_stats=True in InstanceNorm2d to enable them. See the documentation of InstanceNorm2d for details.

**Comment by manikaaggarwal** [comment]
I had the same problem.
Downgrade pytorch version to 0.3.1 and it works.

**Comment by KupynOrest** [comment]
hello, the model was not tested on latesat pytorch version, we would do it in the next version

**Comment by albertchristianto** [comment]
hello @KupynOrest ,
I have tried to lower my pytorch version but still have these problem
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    model = create_model(opt)
  File "/home/tim/Documents/Albert/research/DeblurGAN/models/models.py", line 8, in create_model
    model = TestModel(opt)
  File "/home/tim/Documents/Albert/research/DeblurGAN/models/test_model.py", line 19, in __init__
    opt.learn_residual)
  File "/home/tim/Documents/Albert/research/DeblurGAN/models/networks.py", line 46, in define_G
    gpu_ids=gpu_ids, use_parallel=use_parallel, learn_residual=learn_residual)
  File "/home/tim/Documents/Albert/research/DeblurGAN/models/networks.py", line 124, in __init__
    norm_layer(ngf),
TypeError: __init__() got an unexpected keyword argument 'track_running_stats'


Can you help me with this bug ? 
thank you very much.

best regards,
albert
