### ISSUE TITLE
[ Query ] Will this work for grey scaled images ?

### ISSUE THREAD

**Issue by saurabhvyas** [KupynOrest/DeblurGAN#88]
I am trying to make the model learn unbluring of png images having latex, they are in grey scale, is this a good idea, or its only suitable for realistic images ?

**Comment by gachiemchiep** [comment]
@saurabhvyas 

I think no-one can answer you this question.
Just duplicating 1 gray channel into 3 channel to form a fake RGB image.
Then you can test on DeblurGAN.

Hope you can archive your need soon.

**Comment by saurabhvyas** [comment]
I see, Thanks for your reply

**Comment by IronLavender** [comment]
> I see, Thanks for your reply
So Does your grey input work? I try to duplicate 1 gray channel into 3 channel, but the result of the Network learning seems to be an extra layer of green channels on grey  images. Have you ever been in a situation like this?
![image](https://user-images.githubusercontent.com/23647489/64917985-22e04700-d7ca-11e9-8c33-3da34cbc3076.png)
