### ISSUE TITLE
cannot import name 'SSIM'

### ISSUE THREAD

**Issue by irving-genvis** [KupynOrest/DeblurGAN#9]
Hi anyone encountered this problem? I have installed ssim but cannot import SSIM from it.

**Comment by qinghua2016** [comment]
You need to change the code by "from util.metrics import SSIM".

**Comment by qinghua2016** [comment]
You need to change the code into  "from util.metrics import SSIM".

**Comment by KupynOrest** [comment]
On my second machine method SSIM in util does not work so we've used pyssim library - https://github.com/jterrace/pyssim . I would recommend to use it to compute SSIM metric
