### ISSUE TITLE
Error message when I tried to run combine_A_and_B.py before training

### ISSUE THREAD

**Issue by csqyin** [KupynOrest/DeblurGAN#96]
My command in terminal is: python datasets/combine_A_and_B.py --fold_A ./train --fold_B ./val --fold_AB ./results
and there is error message shown below
[fold_A] =  ./train
[fold_B] =  ./val
[fold_AB] =  ./results
[num_imgs] =  1000000
[use_AB] =  False
Traceback (most recent call last):
  File "datasets/combine_A_and_B.py", line 23, in <module>
    img_list = os.listdir(img_fold_A)
NotADirectoryError: [Errno 20] Not a directory: './train/2163.jpg'

Can anyone please help m with this? Thank you.

**Comment by csqyin** [comment]
Solved

**Comment by liupengfei1234** [comment]
Can you tell me how to fix the problem? Thank you~

**Comment by liupengfei1234** [comment]
@csqyin Can you tell me how to fix the problem? Thank you~

**Comment by csqyin** [comment]
@liupengfei1234 So what is your folder_A and folder_B looks like? Apparently I put images straight in the train folder instead of putting another folder_A inside.

**Comment by liupengfei1234** [comment]
Thanks for reply! I just put images straight in the train folder, but I just put a little images in it, and it comes error as follow:
Traceback (most recent call last):
  File "datasets/combine_A_and_B.py", line 23, in <module>
    img_list = os.listdir(img_fold_A)
NotADirectoryError: [Errno 20] Not a directory: './ima/people_02_kernel_01.png'

**Comment by liupengfei1234** [comment]
Thanks for reply!  Solved

**Comment by robbiewongBD** [comment]
@liupengfei1234 大哥同做去模糊加个微信好不好？

**Comment by csqyin** [comment]
微信号？

**Comment by ski133** [comment]
@liupengfei1234  can you tell me how to fix the problem? Thank you~

**Comment by DrHaqkiem** [comment]
> @liupengfei1234 can you tell me how to fix the problem? Thank you~

did you manage to solve? How?
Can I see your file structure?

**Comment by ski133** [comment]
感谢您的回复，我已经找到了解决的办法了。------------------ 原始邮件 ------------------
发件人: "HaqkiemDaim"<notifications@github.com>
发送时间: 2019年7月21日(星期天) 凌晨4:50
收件人: "KupynOrest/DeblurGAN"<DeblurGAN@noreply.github.com>;
抄送: "ski133"<746467512@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [KupynOrest/DeblurGAN] Error message when I tried to runcombine_A_and_B.py before training (#96)


 
@liupengfei1234 can you tell me how to fix the problem? Thank you~
  
did you manage to solve? How?
 Can I see your file structure?
 
&mdash;

**Comment by aisi746467512** [comment]
网络需要combine清晰图像和模糊图像，这一步的完成可以参考CycleGAN：We provide a python script to generate pix2pix training data in the form of pairs of images {A,B}, where A and B are two different depictions of the same underlying scene. For example, these might be pairs {label map, photo} or {bw image, color image}. Then we can learn to translate A to B or B to A:Create folder /path/to/data with subfolders A and B. A and B should each have their own subfolders train, val, test, etc. In /path/to/data/A/train, put training images in style A. In /path/to/data/B/train, put the corresponding images in style B. Repeat same for other data splits (val, test, etc).Corresponding images in a pair {A,B} must be the same size and have the same filename, e.g., /path/to/data/A/train/1.jpg is considered to correspond to /path/to/data/B/train/1.jpg.

**Comment by ski133** [comment]
------------------ 原始邮件 ------------------
发件人: "AI_SKI"<notifications@github.com>;
发送时间: 2019年7月21日(星期天) 晚上11:56
收件人: "KupynOrest/DeblurGAN"<DeblurGAN@noreply.github.com>;
抄送: "悄然[Camel]"<746467512@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [KupynOrest/DeblurGAN] Error message when I tried to runcombine_A_and_B.py before training (#96)




网络需要combine清晰图像和模糊图像，这一步的完成可以参考CycleGAN：We provide a python script to generate pix2pix training data in the form of pairs of images {A,B}, where A and B are two different depictions of the same underlying scene. For example, these might be pairs {label map, photo} or {bw image, color image}. Then we can learn to translate A to B or B to A:Create folder /path/to/data with subfolders A and B. A and B should each have their own subfolders train, val, test, etc. In /path/to/data/A/train, put training images in style A. In /path/to/data/B/train, put the corresponding images in style B. Repeat same for other data splits (val, test, etc).Corresponding images in a pair {A,B} must be the same size and have the same filename, e.g., /path/to/data/A/train/1.jpg is considered to correspond to /path/to/data/B/train/1.jpg.

**Comment by luoshuifeiyang** [comment]
找到解决办法了。在自己的foldA里建立train和test文件夹，在foldB里建立一样的文件夹，里面包含的文件对应，文件名一样。程序运行就能通过了。另外，使用绝对路径，不要使用相对路径。

**Comment by HassanBinHaroon** [comment]
@haqkiemdaim Are you splitting the train, val and test yourself inside the A and B folder. If not, then you need to do this otherwise you'll get this error.

A   

     train
     val
     test

B

     train
     val
     test
